using System.Security.Cryptography;
using System.Text;
using Mindora.Domain.Common;

namespace Mindora.Domain.Entities;

/// <summary>
/// Represents a secure, time-bounded, single-use linking code generated by a parent
/// to authorize a professional/therapist (Doctor) to monitor a Child.
/// Stores only the cryptographic hash of the code to prevent exposure.
/// </summary>
public class ChildLinkingCode : BaseEntity
{
    public const int DefaultValidityHours = 48;

    public Guid ChildId { get; private set; }
    public string CodeHash { get; private set; } = string.Empty;
    public DateTime CreatedAtUtc { get; private set; }
    public DateTime ExpiresAtUtc { get; private set; }
    public bool IsRedeemed { get; private set; }
    public DateTime? RedeemedAtUtc { get; private set; }
    public Guid? RedeemedByDoctorId { get; private set; }

    // Parameterless constructor for ORM deserialization
    protected ChildLinkingCode() : base()
    {
    }

    public ChildLinkingCode(
        Guid id,
        Guid childId,
        string codeHash,
        DateTime createdAtUtc,
        DateTime expiresAtUtc,
        bool isRedeemed = false,
        DateTime? redeemedAtUtc = null,
        Guid? redeemedByDoctorId = null) : base(id)
    {
        if (childId == Guid.Empty)
        {
            throw new DomainException("ChildId cannot be empty for ChildLinkingCode.");
        }

        if (string.IsNullOrWhiteSpace(codeHash))
        {
            throw new DomainException("CodeHash cannot be empty or whitespace.");
        }

        if (expiresAtUtc <= createdAtUtc)
        {
            throw new DomainException("ExpiresAtUtc must be strictly later than CreatedAtUtc.");
        }

        ChildId = childId;
        CodeHash = codeHash.Trim().ToLowerInvariant();
        CreatedAtUtc = createdAtUtc;
        ExpiresAtUtc = expiresAtUtc;
        IsRedeemed = isRedeemed;
        RedeemedAtUtc = redeemedAtUtc;
        RedeemedByDoctorId = redeemedByDoctorId;
    }

    public static ChildLinkingCode Create(
        Guid childId,
        string codeHash,
        TimeSpan? validity = null,
        DateTime? createdAtUtc = null)
    {
        var created = createdAtUtc ?? DateTime.UtcNow;
        var expires = created.Add(validity ?? TimeSpan.FromHours(DefaultValidityHours));
        return new ChildLinkingCode(Guid.NewGuid(), childId, codeHash, created, expires, false, null, null);
    }

    public bool IsExpired(DateTime utcNow) => utcNow > ExpiresAtUtc;

    public void Redeem(Guid doctorId, DateTime? redeemedAtUtc = null)
    {
        if (doctorId == Guid.Empty)
        {
            throw new DomainException("DoctorId cannot be empty when redeeming linking code.");
        }

        var now = redeemedAtUtc ?? DateTime.UtcNow;

        if (IsRedeemed)
        {
            throw new DomainException("This linking code has already been redeemed.");
        }

        if (IsExpired(now))
        {
            throw new DomainException("This linking code has expired.");
        }

        IsRedeemed = true;
        RedeemedAtUtc = now;
        RedeemedByDoctorId = doctorId;
    }

    public void Expire()
    {
        ExpiresAtUtc = DateTime.UtcNow;
    }

    public static string ComputeHash(string rawCode)
    {
        if (string.IsNullOrWhiteSpace(rawCode))
        {
            return string.Empty;
        }

        // Normalize: uppercase and remove hyphens/spaces, strip optional MND prefix
        var normalized = rawCode.Replace("-", string.Empty).Replace(" ", string.Empty).Trim().ToUpperInvariant();
        if (normalized.StartsWith("MND"))
        {
            normalized = normalized[3..];
        }

        var bytes = Encoding.UTF8.GetBytes(normalized);
        var hashBytes = SHA256.HashData(bytes);
        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }
}
